### ISSUE TITLE
Manually add Attribute to Product

### ISSUE THREAD

**Issue by alch** [elcodi/bamboo-admin#56]
As seen in https://github.com/elcodi/elcodi/issues/374, product attributes need to be manually added before creating `Variant`. The current implementation works only when calling `Variant::setOption()`, which takes care of updating parent product's attributes. When using a form, such method does not get called, so product's attribute must be known before.

**Comment by mmoreram** [comment]
Issue finished and tested in Admin.

Thanks everyone involved :)
