### ISSUE TITLE
Flow in controllers

### ISSUE THREAD

**Issue by xphere** [elcodi/bamboo-admin#60]
Right now the flow in controllers does not depend on the valid state of the form. So it is always:
`new` → `save` → `view`
`edit` → `update` → `view`

But in the cases where `save` or `update` fails (be it by validation or by any other means), we should go back to `new` or `edit` respectively, the form completed as it was sent by the user and errors shown.

**Comment by mmoreram** [comment]
Workflow changed in new controllers!

:)
